#!/bin/bash

# Copyright 2021 Melwyn Francis Carlo

clear

rm -rf ../package/windows/exe/*
rm -rf ../package/windows/msi/*

jpackage -d ../package/windows/exe --verbose \
--type "exe" \
--app-version "1.0" \
--icon ../CodeSnippetsAccumulator/ui/res/img/icon.png \
--copyright "2021 Melwyn Francis Carlo <carlo.melwyn@outlook.com>" \
--description "An app for storing, searching, and retrieving code snippets" \
--name "CodeSnippetsAccumulator" \
--vendor "Melwyn Francis Carlo" \
--input ../jar \
--module-path ../openjfx/windows/jmod \
--add-modules javafx.graphics,javafx.fxml,javafx.controls \
--main-jar CodeSnippetsAccumulator.jar \
--win-menu \
--win-menu-group "Office" \
--win-per-user-install \
--win-shortcut

jpackage -d ../package/windows/msi --verbose \
--type "msi" \
--app-version "1.0" \
--icon ../CodeSnippetsAccumulator/ui/res/img/icon.png \
--copyright "2021 Melwyn Francis Carlo <carlo.melwyn@outlook.com>" \
--description "An app for storing, searching, and retrieving code snippets" \
--name "CodeSnippetsAccumulator" \
--vendor "Melwyn Francis Carlo" \
--input ../jar \
--module-path ../openjfx/windows/jmod \
--add-modules javafx.graphics,javafx.fxml,javafx.controls \
--main-jar CodeSnippetsAccumulator.jar \
--win-menu \
--win-menu-group "Office" \
--win-per-user-install \
--win-shortcut

