#!/bin/bash

# Copyright 2021 Melwyn Francis Carlo

cd ..

java \
--module-path openjfx/linux/sdk \
--add-modules javafx.graphics,javafx.fxml,javafx.controls \
-jar jar/CodeSnippetsAccumulator.jar

cd setup

